---
# handlers for freebsd_pf

# pf -----------------------------------------------------------------
# start, restart, reload of pf break the ssh connection. Sleep for 5
# seconds and let the async/poll to close the connection correctly
# before restarting pf. Shell module must be used instead of service.

- name: start pf
  # service: name="pf" state="started" enabled="yes"
  ansible.builtin.shell:
    cmd: >
      (( sleep 5; nohup service pf start 1>/dev/null 2>&1 ) & )
  async: "{{ pf_async_timeout }}"
  poll: 0
  when:
    - pf_enable|bool
    - not ansible_check_mode
    - not pf_conf_only|bool
  changed_when: pf_enable|bool

- name: disable and stop pf
  ansible.builtin.service:
    name: pf
    state: stopped
    enabled: false

- name: restart pf
  # service: name="pf" state="restarted"
  ansible.builtin.shell:
    cmd: >
      (( sleep 5; nohup service pf restart 1>/dev/null 2>&1 ) & )
  async: "{{ pf_async_timeout }}"
  poll: 0
  when:
    - pf_enable|bool
    - not ansible_check_mode
    - not pf_conf_only|bool
  changed_when: pf_enable|bool

- name: reload pf
  # service: name="pf" state="reloaded"
  ansible.builtin.shell:
    cmd: >
      (( sleep 5; nohup service pf reload 1>/dev/null 2>&1 ) & )
  async: "{{ pf_async_timeout }}"
  poll: 0
  when:
    - pf_enable|bool
    - not ansible_check_mode
    - not pf_conf_only|bool
  changed_when: pf_enable|bool

# EOF
...
